[project]
name = "merchant-integration"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "aiogram==3.13.1",
    "python-dotenv==1.0.0",
    "aiohttp==3.9.1",
]
